---

name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.2.0
        id: go
        with:
          go-version: "^1.18.2"

      - uses: actions/checkout@v3.0.2

      - run: go install github.com/ellisonleao/vl/cmd/vl@latest
      - run: vl -a 403 -t 30s -w poly.pizza,thebloomapp.com,p3nlhclust404.shr.prod.phx3.secureserver.net,horde3d.org,puzzlescript.net,hacknplan.com,taiga.io,p1.untergrund.net README.md 
